print("**********************************************")
print("Bienvenido a la calculadora de 6 operaciones")
print("**********************************************")

print("************* MENU DE OPERACIONES *************")
print("1- SUMA")
print("2- RESTA")
print("3- MULTIPLICACION")
print("4- DIVISION")
print("5- POTENCIACION")
print("6- RADIACION")
print("**********************************************")